version: "2.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - 9200:9200

  postgresql:
    image: postgres:10.5
    environment:
      POSTGRES_USER: "quarkus_test"
      POSTGRES_PASSWORD: "quarkus_test"
      POSTGRES_DB: "quarkus_test"
    ports:
      - "5432:5432"

